### ISSUE TITLE
Error opening file empiar_10087_c2_tomo02.hff

### ISSUE THREAD

**Issue by tomgoddard** [emdb-empiar/sfftk-rw#2]
Using SFFSegmentation.from_file('empiar_10087_c2_tomo02.hff') gives the error below.  This is being called in ChimeraX, using sfftk-rw 0.5.0.dev0.

Startup Messages
warning	'clip' is a prefix of an existing command 'clipper'
UCSF ChimeraX version: 0.91 (2019-10-25)
© 2016-2019 Regents of the University of California. All rights reserved.
How to cite UCSF ChimeraX
open /Users/goddard/ucsf/data/sff/empiar/empiar_10087_c2_tomo02.hffTraceback (most recent call last):
  File "/Users/goddard/ucsf/chimerax/ChimeraX.app/Contents/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sfftkrw/schema/base.py", line 398, in __new__
    assert isinstance(getattr(cls, cls.index_attr), numbers.Integral)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/goddard/ucsf/chimerax/ChimeraX.app/Contents/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chimerax/cmd_line/tool.py", line 254, in execute
    cmd.run(cmd_text)
  File "/Users/goddard/ucsf/chimerax/ChimeraX.app/Contents/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chimerax/core/commands/cli.py", line 2837, in run
    result = ci.function(session, **kw_args)
  File "/Users/goddard/ucsf/chimerax/ChimeraX.app/Contents/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chimerax/core/commands/open.py", line 68, in open
    path_models = session.models.open(paths, format=format, name=name, **kw)
  File "/Users/goddard/ucsf/chimerax/ChimeraX.app/Contents/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chimerax/core/models.py", line 658, in open
    session, filenames, format=format, name=name, **kw)
  File "/Users/goddard/ucsf/chimerax/ChimeraX.app/Contents/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chimerax/core/io.py", line 489, in open_multiple_data
    models, status = open_data(session, fspec, format=format, name=name, **kw)
  File "/Users/goddard/ucsf/chimerax/ChimeraX.app/Contents/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chimerax/core/io.py", line 445, in open_data
    models, status = open_func(*args, **kw)
  File "/Users/goddard/ucsf/chimerax/ChimeraX.app/Contents/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chimerax/emdb_sff/__init__.py", line 24, in open_file
    return sff.read_sff(session, path)
  File "/Users/goddard/ucsf/chimerax/ChimeraX.app/Contents/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chimerax/emdb_sff/sff.py", line 26, in read_sff
    seg = SFFSegmentation.from_file(path)
  File "/Users/goddard/ucsf/chimerax/ChimeraX.app/Contents/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sfftkrw/schema/adapter.py", line 1657, in from_file
    seg._local = seg.from_hff(h)._local
  File "/Users/goddard/ucsf/chimerax/ChimeraX.app/Contents/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sfftkrw/schema/adapter.py", line 1756, in from_hff
    obj.segments = SFFSegmentList.from_hff(hff_data[u'segments'])
  File "/Users/goddard/ucsf/chimerax/ChimeraX.app/Contents/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sfftkrw/schema/adapter.py", line 1305, in from_hff
    S = SFFSegment.from_hff(hff_data[segment_id])
  File "/Users/goddard/ucsf/chimerax/ChimeraX.app/Contents/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sfftkrw/schema/adapter.py", line 1276, in from_hff
    obj.meshes = SFFMeshList.from_hff(hff_data[u"meshes"])
  File "/Users/goddard/ucsf/chimerax/ChimeraX.app/Contents/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sfftkrw/schema/adapter.py", line 1093, in from_hff
    M = SFFMesh.from_hff(hff_data[u"{}".format(mesh_id)])
  File "/Users/goddard/ucsf/chimerax/ChimeraX.app/Contents/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sfftkrw/schema/adapter.py", line 1030, in from_hff
    obj.vertices = SFFVertexList.from_hff(hff_data[u'vertices'])
  File "/Users/goddard/ucsf/chimerax/ChimeraX.app/Contents/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sfftkrw/schema/adapter.py", line 944, in from_hff
    z=float(vertex[u'z'])
  File "/Users/goddard/ucsf/chimerax/ChimeraX.app/Contents/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sfftkrw/schema/base.py", line 400, in __new__
    raise SFFTypeError(cls.index_attr, numbers.Integral)
sfftkrw.schema.base.SFFTypeError: "'vertex_id' is not object of type <class 'numbers.Integral'>"

sfftkrw.schema.base.SFFTypeError: "'vertex_id' is not object of type "

File "/Users/goddard/ucsf/chimerax/ChimeraX.app/Contents/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sfftkrw/schema/base.py", line 400, in __new__
raise SFFTypeError(cls.index_attr, numbers.Integral)

See log for complete Python traceback.

**Comment by paulkorir** [comment]
Fixed in v0.5.1.dev0
